- name: Create vault audit log
  file:
    path: "{{ vault_audit_log }}"
    state: touch
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0600
  changed_when: False
  become: yes

- name: Set up vault audit log rotation
  template:
    src: vault.logrotate.j2
    dest: "{{ vault_logrotate_path }}"
  become: yes
