---

- set_fact:
    console_cert_domains: [ "{{ inventory_hostname }}", "{{ console_vnc_hostname }}" ]

- set_fact:
    console_cert_domains: "{{ console_cert_domains }} + [ '{{ console_dbg_hostname }}' ]"
  when: console_dbg|bool

- import_role:
    name: web
  vars:
    nginx_config_template: nginx-main.j2
    nginx_config_filename: default
    cert_domains: "{{ console_cert_domains }}"
  when: skip_console_setup is not defined or not skip_console_setup
  tags: setup

- name: Load reCAPTCHA key
  import_role:
    name: load-vault-creds
    tasks_from: recaptcha

- name: Deploy production console
  import_role:
    name: console
    tasks_from: console-prod

- name: Deploy debug console
  import_role:
    name: console
    tasks_from: console-dbg
  when: console_dbg is defined and console_dbg|bool

- name: Deploy MC federation proxy
  import_role:
    name: console
    tasks_from: console-mc-fed
  when: federated_mc is defined and federated_mc|bool
