- hosts: vault
  tasks:

    - import_role:
        name: ntp
      tags: setup

    - import_role:
        name: docker
      tags: setup

    - name: Install dependencies
      apt:
        name:
          - python-minimal
          - python-requests
      become: yes

    - name: Install vault status monitor plugin
      copy:
        src: vault/vault-status-monitor.py
        dest: /usr/local/bin/vault-status-monitor.py
        owner: root
        group: root
        mode: 0555
      become: yes

    - import_role:
        name: web
        tasks_from: certs
      vars:
        cert_domains: [ "{{ inventory_hostname }}" ]
        post_renewal_hooks:
          - hook_name: vault_reload_hook
            hook_content: |
              #!/bin/bash
              systemctl reload vault
      tags: setup

    - include_role:
        name: cert_access
      vars:
        cert_hostname: "{{ inventory_hostname }}"
      loop:
        - vault
      loop_control:
        loop_var: cert_user
      tags: setup

    - import_role:
        name: vault
        tasks_from: setup-audit

    - import_role:
        name: vault
        tasks_from: setup-cert-plugin
